'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QuienesSomos

    '''<summary>
    '''L_QUIEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_QUIEN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L_QUIEN_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_QUIEN_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L_MISION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_MISION As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L_MISION_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_MISION_T As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L_VISION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_VISION As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L_VISION_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_VISION_T As Global.System.Web.UI.WebControls.Label
End Class
