'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Clientes

    '''<summary>
    '''hfLeyendasIdiomaActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLeyendasIdiomaActual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfClienteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfClienteID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''gvClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvClientes As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''L_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_NOM_USU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_NOM_USU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNomUsu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomUsu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_CLAVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_CLAVE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClave As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_CLAVE_R control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_CLAVE_R As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClaveR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaveR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_NOMBRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_NOMBRE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_APELLIDO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_APELLIDO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtApellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApellido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_DNI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_DNI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDNI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDNI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_CUIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_CUIT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCUIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCUIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_CALLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_CALLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_ALTURA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_ALTURA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAltura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAltura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_PISO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_PISO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPiso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPiso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_DEPTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_DEPTO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_CODPOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_CODPOS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodPos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_TELEFONO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_TELEFONO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_IVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_IVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIVA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''L_PROV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_PROV As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlProvincia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProvincia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''L_LOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_LOC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLocalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocalidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''B_REG_CLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_REG_CLI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_EDIT_CLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_EDIT_CLI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_CLOSE_AC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_CLOSE_AC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_LIMPIAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_LIMPIAR As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_CONFIRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_CONFIRM As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_CANCELAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_CANCELAR As Global.System.Web.UI.WebControls.Button
End Class
