'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Idiomas

    '''<summary>
    '''hfLeyendasIdiomaActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLeyendasIdiomaActual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''gvIdiomas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvIdiomas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblErrorI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L_COD_IDI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_COD_IDI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlIdioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdioma As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''L_NOM_IDI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_NOM_IDI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIdiomaNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdiomaNombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''B_AGREGAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_AGREGAR As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_MODIF_I control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_MODIF_I As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_ELIMINAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_ELIMINAR As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_LIMPIARI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_LIMPIARI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvLeyendas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLeyendas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblErrorL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L_COD_LEY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_COD_LEY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLeyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLeyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''L_DESC_LEY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_DESC_LEY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLeyDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLeyDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''B_MODIF_L control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_MODIF_L As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''B_LIMPIARL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_LIMPIARL As Global.System.Web.UI.WebControls.Button
End Class
